# Site settings
title: Dan Cobb
description: > # this means to ignore newlines until "baseurl:"
  Dan Cobb's personal site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dancobb.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
